model: tiny_LLaMA_1b
name: tiny_LLaMA_1b

train_data_dir: ${TOKENIZE_DATA_DIR}/open-web-math-pro
val_data_dir: null
out_dir: ${PT_MODEL_OUTPUT_DIR}/exp3/cpt_tinyllama_1b_owm_15B_prox

# hy-params
num_of_nodes: 8
num_of_devices: 8
global_batch_size: 1024
learning_rate: 0.00008
micro_batch_size: 8
max_step: 7500

# token estimation
warmup_steps: 0
log_step_interval: 10
eval_iters: 100
save_step_interval: 500
eval_step_interval: 500
weight_decay: 0.1
beta1: 0.9
beta2: 0.95
grad_clip: 1.0
decay_lr: true
min_lr: 0.000008

is_continue_pt: true
initial_checkpoint_dir: ${PERSONAL_STORAGE_DIR}/ckpts/TinyLlama-1.1B-intermediate-step-1431k-3T/lit_model.pth


is_constant_lr: false
need_to_warm: false
only_validate: false

# wandb
project: ${WANDB_PROJECT}
entity: ${WANDB_ENTITY}
name: cpt_tinyllama_1b_owm_15B_prox

train_data_config:
  - ["llama/train_owm", 1.0]